Repository graphprotocol/graph-node, pull requests merged in 2018-10, with the labels that each got.

#441 travis: Go back to trusty
  .travis.yml
Labels: pending review, review

#435 docs: Add note about missing @entity directive error
  docs/graphql-api.md
Labels: pending review, review

#447 travis: Upload binaries to github releases
  .travis.yml
Labels: pending review, review

#437 Dave update getting started docs, and other supplimentary docs
  README.md
  docs/getting-started.md
  docs/graphql-api.md
Labels: pending review, review

#452 runtime: Export type conversions between `U256` and numerics
  runtime/wasm/src/module/mod.rs
  runtime/wasm/src/module/test.rs
  runtime/wasm/wasm_test/token_to_numeric.ts
  runtime/wasm/wasm_test/token_to_numeric.wasm
Labels: pending review, review

#454 [ethsf] graphql/schema: Replace `.expect` with error
  graphql/src/schema/api.rs
Labels: pending review, review

#456 Add RUST_LOG log level filtering support
  Cargo.lock
  graph/Cargo.toml
  graph/src/lib.rs
  graph/src/util/log.rs
Labels: pending review, review

#458 Add RUST_LOG log level filtering support
  Cargo.lock
  graph/Cargo.toml
  graph/src/lib.rs
  graph/src/util/log.rs
Labels: pending review, review

#453 graphql/schema: Replace `.expect` with error
  graphql/src/schema/api.rs
Labels: pending review, review

#462 Run eth_call on tokio runtime (on ethsf)
  datasource/ethereum/src/ethereum_adapter.rs
  graph/src/components/ethereum/adapter.rs
  runtime/wasm/src/module/mod.rs
Labels: pending review, review

#463 Run eth_call on tokio runtime (on master)
  datasource/ethereum/src/ethereum_adapter.rs
  graph/src/components/ethereum/adapter.rs
  runtime/wasm/src/module/mod.rs
Labels: pending review, review

#461 Add GRAPH_LOG env var, --debug flag (on master)
  graph/src/util/log.rs
  node/src/main.rs
Labels: pending review, review

#460 Add GRAPH_LOG env var, --debug flag (on ethsf)
  graph/src/util/log.rs
  node/src/main.rs
Labels: pending review, review

#464 Limit exponential backoff to 30 seconds
  graph/src/util/futures.rs
Labels: pending review, review

#467 runtime/wasm: Fix mock Ethereum adapter ( on master )
  runtime/wasm/src/module/test.rs
Labels: pending review, review

#468 runtime/wasm: Fix mock Ethereum adapter
  runtime/wasm/src/module/test.rs
Labels: pending review, review

#469 datasource, store: Fix block ingestion on short chains
  datasource/ethereum/src/block_ingestor.rs
  store/postgres/migrations/2018-08-22-140000_create_chain_head_update_procedure/up.sql
Labels: area/ethereum, area/store, pending review, review

#473 graph: Fix with_retry logging messages
  graph/src/util/futures.rs
Labels: pending review, review

#472 graph: Fix with_retry logging messages
  graph/src/util/futures.rs
Labels: pending review, review

#470 Store.set() merges id into the entity before pushing the `EntityOperation`
  runtime/wasm/src/module/mod.rs
Labels: pending review, review

#485 Remove buildkite
  .buildkite/pipeline.deploy-staging-docs.yaml
  .buildkite/pipeline.deploy-staging.yaml
  .buildkite/pipeline.yaml
Labels: pending review, review

#478 datasource, store: Fix block ingestion on short chains
  datasource/ethereum/src/block_ingestor.rs
  store/postgres/migrations/2018-08-22-140000_create_chain_head_update_procedure/up.sql
Labels: area/ethereum, area/store, pending review, review

#496 README: Use --ethereum-rpc instead of --ethereum-ws in instructions
  README.md
Labels: chore, documentation, pending review, review

#498 Fix panic reporting to also report constant strings
  graph/src/util/log.rs
Labels: pending review, review

#508 Handle transaction removed from main chain
  datasource/ethereum/src/block_ingestor.rs
  graph/src/lib.rs
  graph/src/util/futures.rs
Labels: area/ethereum, bug, pending review, review

#511 travis: Deny failures on beta
  .travis.yml
Labels: pending review, review

#516 BlockStream: Change log from `error` to `info`
  datasource/ethereum/src/block_stream.rs
Labels: pending review, review

#509 Readme: Update Ethereum flags
  README.md
Labels: pending review, review

#517 Capitalize logs
  datasource/ethereum/src/block_ingestor.rs
  datasource/ethereum/src/block_stream.rs
  mock/src/server.rs
  server/http/src/server.rs
  server/websocket/src/server.rs
Labels: pending review, review

#520 travis: Fix and refactor style check and release building
  .travis.yml
Labels: pending review, review

#522 Check block hash on old receipts
  datasource/ethereum/src/ethereum_adapter.rs
Labels: area/ethereum, bug, pending review, review

#523 update ganache and debug flag in readme
  README.md
  docs/getting-started.md
Labels: pending review, review

#527 Use address field in eth_getLogs
  datasource/ethereum/src/ethereum_adapter.rs
Labels: area/ethereum, pending review, performance, review

#528 Refactor implementation of host exports into separate module
  runtime/wasm/src/host_exports.rs
  runtime/wasm/src/lib.rs
  runtime/wasm/src/module/mod.rs
  runtime/wasm/src/module/test.rs
Labels: pending review, review
