Repository graphprotocol/graph-node, pull requests merged in 2018-09, with the labels that each got.

#323 Readme: Update postgres flag in cargo
  README.md
Labels: pending review, review

#326 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: pending review, review

#327 Update README.md
  README.md
Labels: pending review, review

#311 Test Ethereum endpoint with get current block_number call
  node/src/main.rs
Labels: pending review, review

#338 json-rpc: Take auth list directly
  Cargo.lock
  server/json-rpc/Cargo.toml
  server/json-rpc/src/lib.rs
Labels: pending review, review

#358 node: Use `version` instead of `add` to test ipfs connectivity
  node/src/main.rs
Labels: pending review, review

#343 runtime: Export `typeConversion.bigIntToInt256`
  runtime/wasm/src/module.rs
Labels: pending review, review

#364 node: Remove IPFS connectivity test
  node/src/main.rs
Labels: bug, pending review, review

#368 rustfmt for Rust 1.29
  core/src/subgraph/provider.rs
  core/tests/tests.rs
  datasource/ethereum/src/block_ingestor.rs
  datasource/ethereum/src/ethereum_adapter.rs
  graph/src/components/ethereum/adapter.rs
  graph/src/components/subgraph/registry.rs
  graph/src/data/query/result.rs
  graph/src/data/subgraph.rs
  graphql/src/execution/execution.rs
  graphql/src/execution/resolver.rs
  graphql/src/introspection/resolver.rs
  graphql/src/query/ast.rs
  graphql/src/schema/api.rs
  graphql/src/schema/ast.rs
  graphql/src/schema/validation.rs
  graphql/src/store/query.rs
  graphql/src/store/resolver.rs
  graphql/tests/query.rs
  mock/src/server.rs
  mock/src/store.rs
  node/src/main.rs
  runtime/wasm/src/asc_abi/test.rs
  runtime/wasm/src/host.rs
  runtime/wasm/src/module.rs
  server/http/src/request.rs
  server/http/src/server.rs
  server/http/src/service.rs
  server/http/src/test_utils.rs
  server/http/tests/server.rs
  server/websocket/src/connection.rs
  server/websocket/src/server.rs
  store/postgres/src/store.rs
  store/postgres/tests/store.rs
Labels: pending review, review

#366 node: do not block on IPFS connection test
  node/src/main.rs
Labels: pending review, review

#382 datasource/ethereum: Add contract address to event filter
  datasource/ethereum/src/ethereum_adapter.rs
Labels: p1, pending review, review

#395 Add EthereumBlockPointer type
  graph/src/components/ethereum/adapter.rs
  graph/src/components/ethereum/mod.rs
  graph/src/lib.rs
Labels: pending review, review

#393 store/postgres: Include subgraph id as input to block revert functions
  store/postgres/migrations/2018-07-10-062730_create_revert_procedures/up.sql
  store/postgres/src/functions.rs
  store/postgres/src/store.rs
Labels: pending review, review

#398 Allow failures on Rust beta
  .travis.yml
Labels: pending review, review

#399 runtime: Remove `block_hash` param from contract calls
  runtime/wasm/src/asc_abi/class.rs
  runtime/wasm/src/lib.rs
  runtime/wasm/src/module.rs
  runtime/wasm/src/to_from/external.rs
Labels: pending review, review

#391 runtime: Fix `ipfs.cat`
  Cargo.lock
  graph/src/components/link_resolver.rs
  runtime/wasm/Cargo.toml
  runtime/wasm/src/host.rs
  runtime/wasm/src/module.rs
  runtime/wasm/wasm_test/ipfs_cat.ts
  runtime/wasm/wasm_test/ipfs_cat.wasm
  runtime/wasm/wasm_test/string_to_number.ts
Labels: pending review, review

#409 Handle IPFS hostname in addition to IP address
  Cargo.lock
  node/Cargo.toml
  node/src/main.rs
Labels: pending review, review

#373 docs: Add info about store.get
  docs/getting-started.md
Labels: pending review, review

#422 Return `null` from store.get if the entity wasn't found
  runtime/wasm/src/module/mod.rs
Labels: area/runtime, enhancement, pending review, review
