Repository graphprotocol/graph-node, pull requests merged in 2018-08, with the labels that each got.

#223 README: Fix cargo run example
  README.md
Labels: pending review, review

#224 Reccomend `--release` in the README.
  README.md
Labels: pending review, review

#240 docs: Minor getting started improvements
  docs/getting-started.md
Labels: pending review, review

#239 Improve event signature matching: event handlers.event no longer sensitive to whitespace
  graph/src/util/ethereum.rs
Labels: pending review, review

#237 Update Apache license to include Graph Protocol copyright specifics
  LICENSE-APACHE
  README.md
Labels: pending review, review

#243 docs: update contributing.md
  CONTRIBUTING.md
Labels: pending review, review

#244 Update README.md
  README.md
Labels: pending review, review

#247 docs: fix broken links
  docs/subgraph-manifest.md
Labels: pending review, review

#251 *: Format for Rust 1.28
  datasource/ethereum/tests/adapter.rs
  graph/src/components/server.rs
  graph/src/data/query/error.rs
  graph/src/data/store/mod.rs
  graph/src/data/subgraph.rs
  graphql/src/query/execution.rs
  graphql/src/store/query.rs
  graphql/src/store/resolver.rs
  graphql/tests/query.rs
  mock/src/server.rs
  runtime/wasm/src/asc_abi/test.rs
  runtime/wasm/src/module.rs
  server/http/src/request.rs
  server/http/src/server.rs
  server/http/src/service.rs
  store/postgres/tests/store.rs
Labels: pending review, review

#256 runtime: Handle all events, merge event streams
  runtime/wasm/src/host.rs
Labels: pending review, review

#258 runtime: Remove block hash from `set`, `remove`, bind it transparently
  docs/getting-started.md
  runtime/wasm/src/module.rs
  runtime/wasm/test/example_event_handler.wasm
Labels: pending review, review

#267 Update code formatting to Rust 1.28.0 standards
  core/src/subgraph/manager.rs
  graph/src/lib.rs
  runtime/wasm/src/module.rs
Labels: pending review, review

#264 Export typeConversion.stringToH160(String): H160 function
  runtime/wasm/src/module.rs
Labels: enhancement, pending review, review

#271 README: Add note about required packages on Ubuntu
  README.md
Labels: pending review, review

#288 Improve contract call type mismatch error
  core/tests/tests.rs
  datasource/ethereum/src/ethereum_adapter.rs
  graph/src/components/ethereum/adapter.rs
Labels: developer experience, pending review, review

#308 Detailed logging of ethereum event handling
  runtime/wasm/src/host.rs
  runtime/wasm/src/module.rs
Labels: pending review, review

#316 docs: Fix link formatting
  docs/graphql-api.md
Labels: pending review, review
