Repository graphprotocol/graph-node, pull requests merged in 2018-11, with the labels that each got.

#542 Organize logging by block & by subgraph
  core/src/subgraph/instance.rs
  core/src/subgraph/instance_manager.rs
  datasource/ethereum/src/block_ingestor.rs
  datasource/ethereum/src/block_stream.rs
  datasource/ethereum/src/ethereum_adapter.rs
  datasource/ethereum/src/lib.rs
  datasource/ethereum/tests/adapter.rs
  graph/src/components/ethereum/adapter.rs
  graph/src/components/subgraph/host.rs
  graph/src/components/subgraph/instance.rs
  graph/src/util/futures.rs
  node/src/main.rs
  runtime/wasm/src/host.rs
  runtime/wasm/src/host_exports.rs
  runtime/wasm/src/lib.rs
  runtime/wasm/src/module/mod.rs
  runtime/wasm/src/module/test.rs
  server/http/src/server.rs
  server/websocket/src/server.rs
  store/postgres/src/store.rs
Labels: area/ethereum, area/runtime, area/subgraphs, enhancement, pending review, review

#548 runtime: `big_int_to_hex` prints in big endian and trims zeros
  graph/src/data/store/scalar.rs
  runtime/wasm/src/host_exports.rs
  runtime/wasm/src/module/test.rs
Labels: pending review, review

#557 runtime: Make error message more user friendly
  runtime/wasm/src/host_exports.rs
Labels: pending review, review

#559 Store updates: log event source of removal operations and make string formatting of block hashes consistent
  store/postgres/src/store.rs
Labels: pending review, review

#568 Fix boolean queries
  store/postgres/src/filter.rs
  store/postgres/tests/store.rs
Labels: area/graphql, pending review, review

#572 Clarify log message
  core/src/subgraph/instance_manager.rs
Labels: area/subgraphs, developer experience, pending review, review

#595 Improve the conflicting entity ID error message
  runtime/wasm/src/host_exports.rs
Labels: developer experience, enhancement, pending review, review

#598 runtime: Accept leading `0x` in `string_to_h160`
  runtime/wasm/src/host_exports.rs
  runtime/wasm/src/module/mod.rs
Labels: pending review, review

#604 node, core: Remove use of `wait` in main
  core/src/subgraph/provider_with_names.rs
  core/tests/tests.rs
  node/src/main.rs
Labels: pending review, review

#602 graph, store, graphql: Add `entityCount` field to subgraph entities
  core/src/subgraph/subgraphs.graphql
  graph/src/components/store.rs
  graph/src/data/query/error.rs
  graph/src/data/subgraph/schema.rs
  graphql/src/store/resolver.rs
  graphql/tests/query.rs
  mock/src/store.rs
  store/postgres/src/store.rs
Labels: pending review, review
