Repository graphprotocol/graph-node, pull requests merged in 2018-12, with the labels that each got.

#627 Add cost column to subgraph_deployments table
  store/postgres/migrations/2018-12-03-150000_add_subgraph_cost/down.sql
  store/postgres/migrations/2018-12-03-150000_add_subgraph_cost/up.sql
Labels: area/store, pending review, review

#635 Update formatting for Rust 1.31
  core/src/log/elastic.rs
  core/src/subgraph/instance_manager.rs
  core/src/subgraph/provider.rs
  core/src/subgraph/provider_with_names.rs
  core/tests/tests.rs
  datasource/ethereum/src/block_ingestor.rs
  datasource/ethereum/src/block_stream.rs
  datasource/ethereum/src/ethereum_adapter.rs
  datasource/ethereum/tests/adapter.rs
  graph/src/components/ethereum/adapter.rs
  graph/src/components/ethereum/types.rs
  graph/src/components/store.rs
  graph/src/data/graphql/validation.rs
  graph/src/data/subgraph/mod.rs
  graph/src/util/futures.rs
  graph/src/util/log.rs
  graphql/src/execution/execution.rs
  graphql/src/execution/resolver.rs
  graphql/src/introspection/resolver.rs
  graphql/src/query/ast.rs
  graphql/src/schema/api.rs
  graphql/src/schema/ast.rs
  graphql/src/store/query.rs
  graphql/src/store/resolver.rs
  graphql/src/values/coercion.rs
  graphql/tests/introspection.rs
  graphql/tests/query.rs
  mock/src/server.rs
  mock/src/store.rs
  mock/src/subgraph.rs
  node/src/main.rs
  runtime/wasm/src/asc_abi/test.rs
  runtime/wasm/src/host.rs
  runtime/wasm/src/host_exports.rs
  runtime/wasm/src/module/mod.rs
  runtime/wasm/src/module/test.rs
  server/http/src/service.rs
  server/http/src/test_utils.rs
  server/http/tests/server.rs
  server/json-rpc/src/lib.rs
  server/websocket/src/connection.rs
  server/websocket/src/server.rs
  store/postgres/src/filter.rs
  store/postgres/src/store.rs
  store/postgres/tests/store.rs
Labels: pending review, review

#632 Refactor subgraph entity logic
  Cargo.lock
  core/src/subgraph/provider.rs
  graph/Cargo.toml
  graph/src/components/store.rs
  graph/src/data/subgraph/schema.rs
  graph/src/lib.rs
  graphql/src/store/resolver.rs
  graphql/tests/query.rs
  mock/src/store.rs
  server/http/src/service.rs
  server/websocket/src/server.rs
  store/postgres/src/store.rs
Labels: area/store, area/subgraphs, pending review, review

#653 server/http: Make GET / always return a 200 page
  server/http/src/service.rs
Labels: enhancement, pending review, review

#650 Use a DB connection pool
  Cargo.lock
  store/postgres/Cargo.toml
  store/postgres/src/store.rs
  store/postgres/tests/store.rs
Labels: pending review, review

#654 Log error on IPFS address resolution failure
  node/src/main.rs
Labels: pending review, review

#656 Accept mappings with no import section
  runtime/wasm/src/module/mod.rs
  runtime/wasm/src/module/test.rs
  runtime/wasm/wasm_test/abort.ts
  runtime/wasm/wasm_test/abort.wasm
  store/postgres/tests/store.rs
Labels: pending review, review
