Repository graphprotocol/graph-node, pull requests merged in 2019-02, with the labels that each got.

#727 Validate block ingestor ancestor count
  datasource/ethereum/src/block_stream.rs
  node/src/main.rs
Labels: code quality, pending review, review

#723 Replace current version with new version if current is not fully synced yet
  core/src/subgraph/registrar.rs
  graph/src/components/store.rs
Labels: pending review, review

#726 Move all web3 calls to EthereumAdapter
  datasource/ethereum/src/block_ingestor.rs
  datasource/ethereum/src/block_stream.rs
  datasource/ethereum/src/ethereum_adapter.rs
  graph/src/components/ethereum/adapter.rs
  graph/src/components/ethereum/mod.rs
  graph/src/lib.rs
  node/src/main.rs
  runtime/wasm/src/module/test.rs
Labels: code quality, enhancement, pending review, review

#737 Use ethabi that allows event overloading
  Cargo.lock
  graph/Cargo.toml
  runtime/wasm/Cargo.toml
Labels: bug, pending review, review

#728 Add multicolumn index to entities table on the subgraph and entity columns
  store/postgres/migrations/2019-02-01-045927_add_entities_indexes/down.sql
  store/postgres/migrations/2019-02-01-045927_add_entities_indexes/up.sql
Labels: pending review, review

#746 Exclude Docker Compose data files from versioning
  .gitignore
Labels: bug, developer experience, pending review, review

#751 Make info logs less verbose: only show logs related to relevant blocks
  core/src/subgraph/instance_manager.rs
  datasource/ethereum/src/block_stream.rs
  graph/src/util/log.rs
  runtime/wasm/src/host.rs
Labels: pending review, review

#750 Update Docker Compose setup and docs for an Ethereum node on the host
  docker/README.md
  docker/docker-compose.yml
  docker/parity/config.toml
  docker/parity/instant_seal.json
  docker/parity/keys/DevelopmentChain/UTC--2018-10-05T18-20-34Z--161c1241-980e-5f5b-532d-28baf4227ff9
  docker/parity/keys/DevelopmentChain/UTC--2018-10-05T18-20-47Z--908cca8a-1f74-4a0c-cde5-91a2a9e75942
  docker/parity/keys/DevelopmentChain/UTC--2018-10-05T18-21-18Z--66e1a88f-0fbb-a905-c2e5-b02480407120
  docker/parity/keys/DevelopmentChain/UTC--2018-10-05T21-11-15Z--e6e3e156-39fa-2676-f62a-8a995ee54d61
  docker/parity/keys/DevelopmentChain/address_book.json
  docker/parity/password.txt
Labels: developer experience, ethdenver, pending review, review

#714 Small updates to the docs that update them to latest commands
  README.md
  docs/getting-started.md
Labels: pending review, review

#758 Return 200 on presence of graphql errors
  server/http/src/response.rs
Labels: pending review, review

#773 store/postgres: enable the pg_stat_statements extension
  store/postgres/migrations/2019-02-25-182843_add_pg_stat_statements/down.sql
  store/postgres/migrations/2019-02-25-182843_add_pg_stat_statements/up.sql
Labels: pending review, review

#778 PSQL version compatibility: use entire function signature in drop function statements
  store/postgres/migrations/2019-02-04-114900_remove_entity_change_triggers/up.sql
Labels: pending review, review

#779 Build subgraph indexes cleanup function: build drop index statements using string concatenation
  store/postgres/migrations/2019-02-26-182914_remove_unassigned_deployment_indexes_procedure/up.sql
Labels: pending review, review

#777 core/subgraph: mark subgraphs as not failed when starting them
  core/src/subgraph/instance_manager.rs
Labels: pending review, review

#784 Make reorg threshold and ancestor count configurable
  Cargo.lock
  node/Cargo.toml
  node/src/main.rs
Labels: enhancement, pending review, review
