Repository graphprotocol/graph-node, pull requests merged in 2019-01, with the labels that each got.

#670 Remove dead code in resolver
  graphql/src/execution/execution.rs
  graphql/src/execution/resolver.rs
  graphql/src/introspection/resolver.rs
  graphql/src/store/resolver.rs
  graphql/tests/introspection.rs
Labels: pending review, review

#675 Add support for variables in subscription queries
  server/websocket/src/connection.rs
Labels: bug, pending review, review

#677 runtime: Inject timeout checks in mappings, log execution time
  Cargo.lock
  core/src/subgraph/instance.rs
  core/tests/tests.rs
  graph/src/components/subgraph/host.rs
  runtime/wasm/Cargo.toml
  runtime/wasm/src/asc_abi/asc_ptr.rs
  runtime/wasm/src/asc_abi/class.rs
  runtime/wasm/src/asc_abi/mod.rs
  runtime/wasm/src/asc_abi/test.rs
  runtime/wasm/src/host.rs
  runtime/wasm/src/host_exports.rs
  runtime/wasm/src/lib.rs
  runtime/wasm/src/module/mod.rs
  runtime/wasm/src/module/test.rs
  runtime/wasm/src/module/test/abi.rs
  runtime/wasm/src/to_from/external.rs
  runtime/wasm/src/to_from/mod.rs
  runtime/wasm/wasm_test/non_terminating.ts
  runtime/wasm/wasm_test/non_terminating.wasm
  runtime/wasm/wasm_test/recompile.sh
Labels: pending review, review

#686 Add environment variable to disable block ingestor
  node/src/main.rs
Labels: pending review, review

#687 runtime: Add `bytes_to_base58` export
  Cargo.lock
  runtime/wasm/Cargo.toml
  runtime/wasm/src/host_exports.rs
  runtime/wasm/src/lib.rs
  runtime/wasm/src/module/mod.rs
  runtime/wasm/src/module/test.rs
  runtime/wasm/wasm_test/bytes_to_base58.ts
  runtime/wasm/wasm_test/bytes_to_base58.wasm
Labels: pending review, review

#689 Allow manual creation of pg_trgm extension in Postgres database
  store/postgres/migrations/2018-12-21-003727_create_attribute_indexing_procedure/up.sql
Labels: pending review, review

#690 Add ETHEREUM_FAST_SCAN_END environment variable
  Cargo.lock
  datasource/ethereum/Cargo.toml
  datasource/ethereum/src/ethereum_adapter.rs
  datasource/ethereum/src/lib.rs
Labels: area/ethereum, enhancement, pending review, review

#681 runtime, graph: Allow panics in mapping runtime threads
  graph/src/util/log.rs
  runtime/wasm/src/host.rs
Labels: pending review, review

#694 Incorporate `cargo fmt` changes for Rust 1.32.0
  graph/src/data/store/mod.rs
  runtime/wasm/src/host.rs
  runtime/wasm/src/host_exports.rs
  runtime/wasm/src/module/mod.rs
  server/http/src/service.rs
  server/websocket/src/connection.rs
  store/postgres/src/filter.rs
  store/postgres/src/store.rs
Labels: pending review, review

#662 Store row level operation type in history, use in revert
  store/postgres/migrations/2019-01-18-195346_update_history_triggers/down.sql
  store/postgres/migrations/2019-01-18-195346_update_history_triggers/up.sql
  store/postgres/migrations/2019-01-18-195526_update_revert_procedures/down.sql
  store/postgres/migrations/2019-01-18-195526_update_revert_procedures/up.sql
Labels: pending review, review

#698 Handle missing block hash on transaction receipts
  datasource/ethereum/src/block_ingestor.rs
  datasource/ethereum/src/ethereum_adapter.rs
Labels: pending review, review

#701 Serialize warnings to Elasticsearch as 'warning', not 'warn'
  core/src/log/elastic.rs
Labels: bug, pending review, review

#699 Add optional environment variables EXTERNAL_{HTTP,WS}_BASE_URL
  Cargo.lock
  server/json-rpc/Cargo.toml
  server/json-rpc/src/lib.rs
Labels: enhancement, pending review, review

#705 server/websocket: Make URL path parsing more robust
  server/websocket/src/server.rs
Labels: bug, pending review, review

#706 Allow failiure of subgraph at start
  core/src/subgraph/registrar.rs
Labels: pending review, review

#708 Limit max ipfs file size through env var
  graph/src/components/link_resolver.rs
Labels: pending review, review

#711 Limit log stream range size
  datasource/ethereum/src/block_stream.rs
Labels: pending review, review
