Repository graphprotocol/graph-node, pull requests merged in 2019-04, with the labels that each got.

#847 store/postgres: fix bug in attempt_chain_head_update for short chains
  store/postgres/migrations/2019-03-31-010824_short_chain_head_update/down.sql
  store/postgres/migrations/2019-03-31-010824_short_chain_head_update/up.sql
Labels: area/ethereum, bug, pending review

#852 Log reason for terminating runtime thread
  runtime/wasm/src/host.rs
Labels: pending review

#855 Bump our ethabi fork for the indexed param fix
  Cargo.lock
Labels: adoption-blocker, area/ethereum, bug, pending review

#867 Update README for infura endpoint change
  README.md
Labels: pending review

#870 Remove `unwrap` left behind
  graphql/src/execution/execution.rs
Labels: pending review

#872 Note on value of `GRAPH_GRAPHQL_MAX_COMPLEXITY`
  docs/environment-variables.md
Labels: pending review

#875 graph: Log the error when retrying
  graph/src/util/futures.rs
Labels: pending review

#876 Add env vars for range size & parallel ranges
  datasource/ethereum/src/ethereum_adapter.rs
  docs/environment-variables.md
Labels: area/ethereum, enhancement, pending review

#877 Pass only the handler name in `HandleEventRequest`
  runtime/wasm/src/host.rs
Labels: pending review

#878 Test fragments
  core/tests/interfaces.rs
Labels: pending review

#882 Make subgraph logs less scary by using "updates" instead of "restarts"
  core/src/subgraph/instance_manager.rs
Labels: area/subgraphs, developer experience, enhancement, pending review

#883 Measure contract call time
  runtime/wasm/src/host_exports.rs
Labels: pending review

#885 Reduce logging volume by removing unnecessary logs
  core/src/subgraph/instance_manager.rs
  datasource/ethereum/src/block_stream.rs
Labels: pending review

#891 Use a shared `ChainHeadUpdateListener` to avoid too many Postgres connections
  datasource/ethereum/src/block_stream.rs
  graph/src/components/ethereum/listener.rs
  graph/src/components/ethereum/mod.rs
  graph/src/components/store.rs
  graph/src/lib.rs
  mock/src/store.rs
  store/postgres/src/chain_head_listener.rs
  store/postgres/src/store.rs
Labels: area/ethereum, area/store, bug, pending review

#893 Print version information on startup
  Cargo.lock
  node/Cargo.toml
  node/src/main.rs
Labels: developer experience, new feature, pending review

#894 Remove noisy log
  graph/src/components/store.rs
Labels: pending review

#897 Log `store.get` time
  runtime/wasm/src/host_exports.rs
Labels: pending review

#853 Don't print passwords from URLs in the logs
  Cargo.lock
  graph/Cargo.toml
  graph/src/util/mod.rs
  graph/src/util/security.rs
  node/src/main.rs
  store/postgres/src/store.rs
Labels: pending review

#901 Add undeployed hint to `currentVersion` error
  graph/src/components/store.rs
Labels: area/subgraphs, developer experience, pending review
