Repository graphprotocol/graph-node, pull requests merged in 2019-05, with the labels that each got.

#904 Fix validation to detect call/block handlers correctly
  core/src/subgraph/validation.rs
Labels: area/subgraphs, bug, pending review

#906 Fix writing and loading of dynamically created data sources
  graph/src/data/subgraph/schema.rs
Labels: accepted, area/subgraphs, p1, pending review

#898 store/postgres: reset pg_stat_statements after a database migration
  store/postgres/src/store.rs
Labels: pending review

#909 core/tests: Fix a number of 'unused variable' warnings
  core/tests/tests.rs
  runtime/wasm/src/module/test.rs
Labels: pending review

#918 Check for contention in DB connection pool
  store/postgres/src/store.rs
Labels: pending review

#921 Use crossbeam channel for tokio contention check
  Cargo.lock
  node/Cargo.toml
  node/src/main.rs
Labels: bug, pending review

#922 store/postgres: make sure only one graph-node runs database migrations
  store/postgres/src/store.rs
Labels: pending review

#923 store/postgres: make store_entity_count migration more robust
  store/postgres/migrations/2019-05-03-164052_store_entity_count/up.sql
Labels: pending review

#929 Don't block updates on a full channel
  store/postgres/src/chain_head_listener.rs
Labels: bug, p1, pending review

#933 Include arguments to log in ElasticSearch log as a map
  graph/src/log/elastic.rs
Labels: pending review

#935 Fix source of log argument kvs for Elasticsearch
  graph/src/log/elastic.rs
Labels: pending review

#945 store/postgres: Add an index on event_meta_data(source)
  store/postgres/migrations/2019-05-14-200255_event_meta_data_source_index/down.sql
  store/postgres/migrations/2019-05-14-200255_event_meta_data_source_index/up.sql
Labels: pending review

#944 graph/data: Ensure we index foreign keys in the GraphQL schema
  graph/src/data/subgraph/schema.rs
Labels: pending review
