Repository graphprotocol/graph-node, pull requests merged in 2019-03, with the labels that each got.

#786 store/postgres: optimize stored proc attempt_chain_head_update
  store/postgres/migrations/2019-02-28-190800_update_chain_head_update_procedure/down.sql
  store/postgres/migrations/2019-02-28-190800_update_chain_head_update_procedure/up.sql
Labels: pending review, review

#790 Fix deprecation warnings for Rust 1.33
  core/tests/tests.rs
  graph/src/components/ethereum/listener.rs
  graph/src/components/link_resolver.rs
  graph/src/data/store/scalar.rs
  graph/src/data/subgraph/mod.rs
  graphql/src/schema/ast.rs
  runtime/wasm/src/host_exports.rs
Labels: pending review, review

#791 travis: increase timeout for cahce pushes
  .travis.yml
Labels: pending review, review

#792 travis: reduce the amount of build data we cache
  .travis.yml
  .travis/before_cache.sh
Labels: pending review, review

#800 attempt_chain_head_update SQL function gets stuck in infinite loop
  store/postgres/migrations/2019-03-04-235349_empty-ethereum-network-chain-head-update-fix/down.sql
  store/postgres/migrations/2019-03-04-235349_empty-ethereum-network-chain-head-update-fix/up.sql
Labels: pending review, review

#802 Cargo: Bump ethabi to pull in the latest patches
  Cargo.lock
Labels: area/ethereum, bug, pending review, review

#804 graphql: Remove unsupported query parameters
  graph/src/data/query/error.rs
  graphql/src/schema/api.rs
Labels: bug, pending review, review

#808 Improve how we record and handle entity_history
  store/postgres/migrations/2019-03-07-171355_update_history_storage/down.sql
  store/postgres/migrations/2019-03-07-171355_update_history_storage/up.sql
  store/postgres/src/functions.rs
  store/postgres/src/store.rs
  store/postgres/src/store_events.rs
  store/postgres/tests/store.rs
Labels: pending review, review

#821 store/postgres: fix syntax error with Postgres 9.6
  store/postgres/migrations/2019-03-07-171355_update_history_storage/up.sql
Labels: pending review

#824 Fail subgraphs that don't start
  core/src/subgraph/provider.rs
  core/src/subgraph/registrar.rs
Labels: bug, pending review

#828 Log error that terminated a mapping
  runtime/wasm/src/host.rs
Labels: pending review

#825 Improve data parsing errors in runtime hosted parsing functions
  runtime/wasm/src/host_exports.rs
Labels: pending review
